## Predicting the Diabetes
#### Building a neural network to accurately predict whether or not the patients in the dataset have diabetes or not?



In [1]:
# Importing required libraries
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.models import model_from_json

In [2]:
# Loading the data
df = np.loadtxt('pima-indians-diabetes.csv', delimiter=',')
df

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

### Preparing the data

In [3]:
#  Splitting the data into dependent and independent variables
X = df[:,0:8]
y = df[:,8]

### Neural Network

In [4]:
# Building the neural network model
model = Sequential()
model.add(Dense(12,input_dim=8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [5]:
# Summary of the neural network
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                108       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [6]:
# Compiling the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [7]:
# Applying the data to the model
model.fit(X,y,epochs=150,batch_size=32)

Epoch 1/150
24/24 [==============================] - 0s 1ms/step - loss: 9.8641 - accuracy: 0.6497
Epoch 2/150
24/24 [==============================] - 0s 1ms/step - loss: 2.8513 - accuracy: 0.6237
Epoch 3/150
24/24 [==============================] - 0s 1ms/step - loss: 1.2935 - accuracy: 0.5690
Epoch 4/150
24/24 [==============================] - 0s 1ms/step - loss: 1.0508 - accuracy: 0.5885
Epoch 5/150
24/24 [==============================] - 0s 1ms/step - loss: 0.9722 - accuracy: 0.5977
Epoch 6/150
24/24 [==============================] - 0s 2ms/step - loss: 0.8788 - accuracy: 0.5951
Epoch 7/150
24/24 [==============================] - 0s 1ms/step - loss: 0.8280 - accuracy: 0.6016
Epoch 8/150
24/24 [==============================] - 0s 1ms/step - loss: 0.7808 - accuracy: 0.6172
Epoch 9/150
24/24 [==============================] - 0s 1ms/step - loss: 0.7339 - accuracy: 0.6211
Epoch 10/150
24/24 [==============================] - 0s 1ms/step - loss: 0.7083 - accuracy: 0.6224
Epoch 11/

In [8]:
# Evaluating the model
model.evaluate(X,y)

24/24 [==============================] - 0s 1ms/step - loss: 0.5029 - accuracy: 0.7474


[0.5029215216636658, 0.7473958134651184]

### Saving the model

In [9]:
# Saving the model into json file 
savemodel = model.to_json()
with open('model.json','w') as json_file:
    json_file.write(savemodel)
model.save_weights('model.h5')

In [10]:
# Opening the json model from the disk 
json_file = open('model.json','r')
json_model_loded = json_file.read()
json_file.close()
model = model_from_json(json_model_loded)
model.load_weights('model.h5')

### Prediction the class using the neural network model

In [12]:
# Predicting the class using some data
val1 = [[5,150,70,14,80,31.1,0.142,21]]
pred1 = model.predict_classes(val1)
pred1

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[0]])

In [13]:
val2 = [[6,121,90,21,56,40,121,14]]
pred2 = model.predict_classes(val2)
pred2

array([[1]])

In [14]:
val3 = [[1,93,70,31,0,30.4,0.315,23]]
pred3 = model.predict_classes(val3)
pred3

array([[0]])